[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 5
maxMessageSize = 50

[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
